### ISSUE TITLE
Transmitter doesn't pick up indirect signals

### ISSUE THREAD

**Issue by DoctorSigma** [dannydjdk/Ranged-Wireless-Redstone#2]
Hi! Decided to try to transmit a signal but it doesn't work, what am I doing wrong?
![image](https://user-images.githubusercontent.com/93322905/144634729-e50e5823-d0bd-42f6-9fa2-b6cbe7703eab.png)
When I press the button the signal is not transmitted, the channels in the transmitter and receiver are the same

**Comment by dannydjdk** [comment]
The transmitter does need to receive a direct signal. So, even though that cobblestone block has a signal, is doesn't output one. You'll need a piece of redstone dust, or a repeater or something that outputs a direct redstone signal.

I do plan to add support for this in the future.

**Comment by dannydjdk** [comment]
Fixed in latest release in each of the 3 Minecraft versions.
